-- liquibase formatted sql
-- changeset kunwoongkim:sprint7.003.create_table_for_driving:0001.create_table_driving_reg
create table driving_reg (
    driving_id	        varchar(12) not null comment '운행ID',
    route_naming	    varchar(13)	comment '편명',
    departure_tml_cd	varchar(3)	comment '출발터미널코드',
    departure_tml_nm	varchar(7)	comment '출발터미널명',
    departure_territory_cd	varchar(2)	comment '출발권역코드',
    arrival_tml_cd	    varchar(3)	comment '도착터미널코드',
    arrival_tml_nm	    varchar(7)	comment '도착터미널명',
    arrival_territory_cd	varchar(2)	comment '도착권역코드',
    driving_status	    varchar(8)	comment '운행상태',
    driver_nm	        varchar(30)	comment '기사명',
    seal	            varchar(7)	comment 'SEAL',
    vehicle_model_cd	varchar(2)	comment '차종코드',
    naked_eye_load_ratio	smallint	comment '육안적재비율',
    departure_tm	    varchar(4)	comment '출발시각',
    arrival_tm	        varchar(4)	comment '도착시각',
    vehicle_no	        varchar(12)	comment '차량번호',
    chassis_no	        varchar(12)	comment '샤시번호',
    stopover_yn	        varchar(1)	comment '경유지여부',
    reg_emp_no	        varchar(7)	comment '등록사원번호',
    reg_dtm	            datetime	comment '등록일시',
    mod_emp_no	        varchar(7)	comment '수정사원번호',
    mod_dtm	            datetime	comment '수정일시',
constraint pk_driving_reg primary key (driving_id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment '출도착 등록';

-- liquibase formatted sql
-- changeset kunwoongkim:sprint7.003.create_table_for_driving:0002.create_table_driving_query
create table driving_query (
    driving_id	            varchar(12)	    not null comment '운행ID',
    route_id	            varchar(10)	    not null comment '노선ID',
    route_naming	        varchar(13)	    not null comment '편명',
    driving_dtm	            datetime	    not null comment '운행일시',
    driving_status	        varchar(8)	    comment '운행상태',
    driving_type	        varchar(2)	    comment '운행타입',
    request_reason	        varchar(1000)	comment '요청사유',
    request_emp_no	        varchar(7)	    comment '요청사원번호',
    request_dtm	            datetime		comment '요청일시',
    settlement_org_cd	    varchar(3)	    comment '정산조직코드',
    distance	            int		        comment '거리',
    charge	                bigint		    comment '운임',
    confirmation_charge 	bigint		    comment '확정운임',
    vehicle_in_tm	        varchar(4)	    comment '입차시각',
    approval_status	        varchar(8)	    comment '승인상태',
    approval_dtm	        datetime		comment '승인일시',
    sales_office_burden_ratio	smallint	comment '영업소부담비율',
    vehicle_vendor_nm	    varchar(20)	    comment '간선사명',
    charger_nm	            varchar(30)	    comment '담당자명',
    address	                varchar(200)	comment '주소',
    vehicle_dispatching_dtm	datetime		comment '배차일시',
    vehicle_dispatching_status	varchar(8)	comment '배차상태',
    vehicle_no	            varchar(12)	    comment '차량번호',
    driver_contact_place	varchar(20)	    comment '기사연락처',
    vehicle_model_cd	    varchar(2)	    comment '차종코드',
    departure_tml_cd	    varchar(3)	    comment '출발터미널코드',
    departure_tml_nm	    varchar(7)	    comment '출발터미널명',
    departure_territory_cd	varchar(2)	    comment '출발권역코드',
    arrival_tml_cd	        varchar(3)	    comment '도착터미널코드',
    arrival_tml_nm	        varchar(7)	    comment '도착터미널명',
    arrival_territory_cd	varchar(2)	    comment '도착권역코드',
    expectation_departure_tm	varchar(4)	comment '예상출발시각',
    expectation_arrival_tm	varchar(4)	    comment '예상도착시각',
    departure_tm	        varchar(4)	    comment '출발시각',
    arrival_tm	            varchar(4)	    comment '도착시각',
    driver_nm	            varchar(30)	    comment '기사명',
    seal	                varchar(7)	    comment 'SEAL',
    stopover_yn	            varchar(1)	    comment '경유지여부',
    chassis_no	            varchar(12)	    comment '샤시번호',
    constraint pk_driving_query primary key (driving_id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment '운영 조회';

-- liquibase formatted sql
-- changeset kunwoongkim:sprint7.003.create_table_for_driving:0003.create_table_driving_result
create table driving_result (
    driving_id	            varchar(12)	    not null comment '운행ID',
    route_id	            varchar(10)	    not null comment '노선ID',
    route_naming	        varchar(13)	    not null comment '편명',
    driving_dtm	            datetime	    not null comment '운행일시',
    driving_status	        varchar(8)	    comment '운행상태',
    driving_type	        varchar(2)	    comment '운행타입',
    request_reason	        varchar(1000)	comment '요청사유',
    request_emp_no	        varchar(7)	    comment '요청사원번호',
    request_dtm	            datetime		comment '요청일시',
    settlement_org_cd	    varchar(3)	    comment '정산조직코드',
    distance	            int		        comment '거리',
    charge	                bigint		    comment '운임',
    confirmation_charge 	bigint		    comment '확정운임',
    vehicle_in_tm	        varchar(4)	    comment '입차시각',
    approval_status	        varchar(8)	    comment '승인상태',
    approval_dtm	        datetime		comment '승인일시',
    sales_office_burden_ratio	smallint	comment '영업소부담비율',
    vehicle_vendor_nm	    varchar(20)	    comment '간선사명',
    charger_nm	            varchar(30)	    comment '담당자명',
    address	                varchar(200)	comment '주소',
    vehicle_dispatching_dtm	datetime		comment '배차일시',
    vehicle_dispatching_status	varchar(8)	comment '배차상태',
    vehicle_no	            varchar(12)	    comment '차량번호',
    driver_contact_place	varchar(20)	    comment '기사연락처',
    vehicle_model_cd	    varchar(2)	    comment '차종코드',
    departure_tml_cd	    varchar(3)	    comment '출발터미널코드',
    departure_tml_nm	    varchar(7)	    comment '출발터미널명',
    departure_territory_cd	varchar(2)	    comment '출발권역코드',
    arrival_tml_cd	        varchar(3)	    comment '도착터미널코드',
    arrival_tml_nm	        varchar(7)	    comment '도착터미널명',
    arrival_territory_cd	varchar(2)	    comment '도착권역코드',
    expectation_departure_tm	varchar(4)	comment '예상출발시각',
    expectation_arrival_tm	varchar(4)	    comment '예상도착시각',
    departure_tm	        varchar(4)	    comment '출발시각',
    arrival_tm	            varchar(4)	    comment '도착시각',
    driver_nm	            varchar(30)	    comment '기사명',
    seal	                varchar(7)	    comment 'SEAL',
    stopover_yn	            varchar(1)	    comment '경유지여부',
    chassis_no	            varchar(12)	    comment '샤시번호',
    load_ratio	            smallint		comment '적재비율',
    rt_qty	                int		        comment 'RT수량',
    rt_load_cargo	        int		        comment 'RT상차',
    pouch_qty	            int		        comment '행낭수량',
    pouch_no_cnt	        int		        comment '행낭개수',
    bulk_no_cnt	            int		        comment '벌크개수',
    constraint pk_driving_result primary key (driving_id)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment '운영 결과';
